name: black reformat

on:
  push:
    branches-ignore:
      - 'main'
jobs:
  linter_name:
    name: runner/black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". -S"
      - name: Create Commit
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: ":art: Format Python code with psf/black"
            